//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;



using TechnicalTest.DataLayer;
using TechnicalTest.CrossLayer;

namespace TechnicalTest.DataLayer
{
    
    ///<sumary>
    ///Base contract for context in Main Module 
    ///</sumary>
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public interface ITechnicalTestUnitOfWork :IQueryableUnitOfWork
    {
       
        #region ObjectSet Properties
    
        IObjectSet<Product> Products{get;}
        
    
        IObjectSet<ProductCategory> ProductCategories{get;}
        
    
        IObjectSet<ProductModel> ProductModels{get;}
        

        #endregion

    
    }
}
	
